## BAsic NumPy

In [72]:
import math 
import numpy as np, nan


In [4]:
# Create a single dimensional array

a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
# Check type of a 
type(a)

numpy.ndarray

In [6]:
b=np.array((2,3,4))
b

array([2, 3, 4])

In [12]:
# How to Create a Multi-dimensional Array.

c = np.array([(1,2,3), (4,5,6)])
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [18]:
d = np.array( [[1,2,3], [4,5,6], [7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# .ndim

In [19]:
# ndarray.ndim

x1 = np.array([1,2,1])
# x1 has one axis. That axis has 3 elements
#x1 has length 3

x1.ndim

1

In [39]:
x2 = np.array([(1,2,3), (4,5,6)])
x2.ndim
#x2 has 2 axes
#The first axis has a lenth of 2
#The second axis has a lenth of 2
print(np.sqrt(x2))
#print(x2.sqrt(x2))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


# dtype

In [25]:
#Find the data type
print(x1.dtype)

int32


x3 = np.array([[1.1,2,3], (3,4,4)])
x3.dtype

In [30]:
# Size of each item => The output means that each element occupies 4 bytes in th numpy array
a1 = np.array([(1,2,3)])
print(a1.itemsize)

4


In [31]:
#ndarray.shape
# (rows, column)
x2.shape

(2, 3)

In [53]:
a=np.array([(1,2,3),(3,4,5,)])

print(a[1,2])


5


In [59]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
import numpy as np
nan = np.nan
n = np.array([[nan, 0.30163819, nan],
       [0.54629113, 0.67017515, 0.9620984 ],
       [0.71410713, nan, 0.56288168],
       [ nan, 0.60435705, 0.83555395]])
n

array([[       nan, 0.30163819,        nan],
       [0.54629113, 0.67017515, 0.9620984 ],
       [0.71410713,        nan, 0.56288168],
       [       nan, 0.60435705, 0.83555395]])